services:
  - type: web
    name: rag-pipeline
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
      - key: DEFAULT_TOP_K
        value: 5
      - key: SIMILARITY_THRESHOLD
        value: 0.7
      - key: DATA_DIR
        value: /tmp/data
      - key: VECTOR_STORE_PATH
        value: /tmp/data/vector_store
      - key: DATABASE_URL
        value: sqlite:////tmp/data/documents.db